package com.votol.configurator;
import android.app.*;import android.os.*;import android.Manifest;import android.content.*;import android.net.Uri;import android.bluetooth.*;import android.content.pm.PackageManager;import android.webkit.*;import java.io.*;import java.util.*;import org.json.JSONObject;
public class MainActivityV2 extends Activity{
 static final int EXPORT_LOG=7001; String pendingLog="";
 WebView w;BluetoothAdapter a;BluetoothSocket s;InputStream in;OutputStream out;volatile boolean run;static final UUID SPP=UUID.fromString("00001101-0000-1000-8000-00805F9B34FB");
 public void onCreate(Bundle b){super.onCreate(b);w=new WebView(this);w.getSettings().setJavaScriptEnabled(true);w.getSettings().setDomStorageEnabled(true);w.addJavascriptInterface(new Bridge(),"AndroidVotol");setContentView(w);w.loadUrl("file:///android_asset/index_v3.html");BluetoothManager m=(BluetoothManager)getSystemService(BLUETOOTH_SERVICE);a=m==null?null:m.getAdapter();if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},9);}
 class Bridge{@JavascriptInterface public void scanClassic(){runOnUiThread(()->pick());}@JavascriptInterface public void disconnect(){close();}@JavascriptInterface public void exportLog(String log){pendingLog=log==null?"":log;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"VOTOL-Monitor-HEX-Log-"+new java.text.SimpleDateFormat("yyyyMMdd-HHmmss",java.util.Locale.US).format(new java.util.Date())+".txt");startActivityForResult(i,EXPORT_LOG);}@JavascriptInterface public void send(String h){try{if(out==null)throw new IOException("Not connected");byte[] d=parse(h);out.write(d);out.flush();emit("classicTx",hex(d));}catch(Exception e){emit("classicError",e.toString());}}}
 void pick(){if(a==null){emit("classicError","Bluetooth tidak tersedia");return;}if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED){emit("classicError","Izin Bluetooth belum diberikan");return;}if(!a.isEnabled()){emit("classicError","Aktifkan Bluetooth");return;}ArrayList<BluetoothDevice> d=new ArrayList<>(a.getBondedDevices());String[] n=new String[d.size()];for(int i=0;i<d.size();i++)n[i]=(d.get(i).getName()==null?"Unknown":d.get(i).getName())+"\n"+d.get(i).getAddress();new AlertDialog.Builder(this).setTitle("Bluetooth Classic / SPP").setItems(n,(x,i)->connect(d.get(i))).setNegativeButton("Batal",null).show();}
 void connect(BluetoothDevice d){new Thread(()->{try{close();if(a.isDiscovering())a.cancelDiscovery();emit("classicConnecting",d.getName());try{s=d.createRfcommSocketToServiceRecord(SPP);s.connect();}catch(Exception secure){emit("classicError","Secure SPP gagal, coba Insecure SPP...");close();s=d.createInsecureRfcommSocketToServiceRecord(SPP);s.connect();}in=s.getInputStream();out=s.getOutputStream();run=true;emit("classicConnected",d.getName()+" [SPP]");reader();}catch(Exception e){emit("classicError","Gagal: "+e);close();}}).start();}
 void reader(){new Thread(()->{byte[] b=new byte[1024];while(run&&in!=null)try{int n=in.read(b);if(n>0)emit("classicRx",hex(Arrays.copyOf(b,n)));else break;}catch(Exception e){if(run)emit("classicError","RX: "+e);}if(run)close();}).start();}
 synchronized void close(){run=false;try{if(in!=null)in.close();}catch(Exception e){}try{if(out!=null)out.close();}catch(Exception e){}try{if(s!=null)s.close();}catch(Exception e){}in=null;out=null;s=null;emit("classicDisconnected","");}
 void emit(String t,String v){runOnUiThread(()->w.evaluateJavascript("window.votolNativeEvent&&window.votolNativeEvent("+JSONObject.quote(t)+","+JSONObject.quote(v)+")",null));}
 static byte[] parse(String h){String[] p=h.trim().split("\\s+");byte[] b=new byte[p.length];for(int i=0;i<p.length;i++)b[i]=(byte)Integer.parseInt(p[i],16);return b;}
 static String hex(byte[] b){StringBuilder x=new StringBuilder();for(byte v:b){if(x.length()>0)x.append(' ');x.append(String.format("%02x",v&255));}return x.toString();}
 protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==EXPORT_LOG&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){try{OutputStream os=getContentResolver().openOutputStream(data.getData());if(os!=null){os.write(pendingLog.getBytes("UTF-8"));os.close();emit("classicInfo","LOG EXPORTED");}}catch(Exception e){emit("classicError","Export log gagal: "+e);}}pendingLog="";} protected void onDestroy(){close();super.onDestroy();}
}